name: Generates Pong SVGs every day

on:
  schedule:
      - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-pong-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pong SVGs
        uses: st1vms/PongSVG@v1.2.0
        with:
          winning-score: 3
          mode: "follower"

      - name: Move generated SVGs and Assets
        run: |
          mkdir -p images
          mv pong_light.svg images/pong_light.svg
          mv pong_dark.svg images/pong_dark.svg
          # Sposta l'immagine scaricata nella stessa cartella degli SVG
          if [ -f "ball_avatar.png" ]; then
            mv ball_avatar.png images/ball_avatar.png
          fi

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs and Assets
        run: |
          # Aggiungi tutto il contenuto della cartella images
          git add images/pong_light.svg images/pong_dark.svg images/ball_avatar.png
          git commit -m "Update Pong SVGs and avatar asset"
          git push

